name: Deploy Go Application

on:
  push:
    branches:
      - deploy-to-ec2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "DATABASE_NAME=${{secrets.DATABASE_NAME}}" >> .env
          echo "MONGODB_URI=${{secrets.MONGODB_URI}}" >> .env

      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build Docker Image
        run: docker build -t jefferyokesamuel/christville .

      - name: Push Image to Docker Hub
        run: docker push jefferyokesamuel/christville:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Pull Docker Image
        run: docker pull jefferyokesamuel/christville:latest

      - name: List Local Docker Images
        run: docker images

      - name: Create Docker Compose 
        run: |
          echo "version: '3.8'
          services:
            app:
              image: jefferyokesamuel/christville:latest
              container_name: christ-container
              restart: always
              ports:
                - '8080:8080'
              environment:
                DATABASE_NAME: ${{secrets.DATABASE_NAME}}
                MONGODB_URI: ${{secrets.MONGODB_URI}}" > docker-compose.yml

      - name: Deploy with Docker Compose
        run: |
          docker-compose down || true
          docker-compose up -d
